"""define sensors effeciently

Revision ID: 08af1ee6ed84
Revises: 
Create Date: 2026-06-20 00:58:16.966842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08af1ee6ed84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('loc_x', sa.Float(), nullable=False),
    sa.Column('loc_y', sa.Float(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('humidity', name='sensortype'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_sensor_id'), 'sensor_data', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_timestamp'), 'sensor_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_timestamp'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_sensor_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_table('sensors')
    op.drop_table('plots')
    # ### end Alembic commands ###
