"""plot dimensions

Revision ID: 0f01bd3a7589
Revises: 08af1ee6ed84
Create Date: 2026-06-23 18:28:56.632738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f01bd3a7589'
down_revision: Union[str, Sequence[str], None] = '08af1ee6ed84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('width', sa.Float(), nullable=False))
    op.add_column('plots', sa.Column('height', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'height')
    op.drop_column('plots', 'width')
    # ### end Alembic commands ###
